# Generated by Django 6.0.3 on 2026-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_alter_emberuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emberuser',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
